### ISSUE TITLE
Uid in to_dict 

### ISSUE THREAD

**Issue by vladimirnani** [smarttradeapp/django_cbtools#28]
There is uid in `to_dict()` method in `CouchbaseNestedModel`
`d['uid'] = self.get_uid()`
Would be useful to add it also to `CouchbaseModel`.

What do you think?

**Comment by iutinvg** [comment]
Don't think so because this dictionary is used to send data to sync-gateway. So sync-gateway will save document ID as a document field, which is not what we want.

**Comment by vladimirnani** [comment]
Ah..ok. I only need it because im doing query `query_objects('by_channel', key, Job)` and then `[o.to_dict() for o in objects]` returning in json response. I guess its Serializers job then right?

**Comment by iutinvg** [comment]
In any place, but outside of `to_dict`.
